# Python Assignment 6: Array Operations using NumPy

## Numpy Operations:  


In [1]:
import numpy as np

### 1.	Create NumPy Arrays:

In [13]:
temperatures_w1 =np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

### 2.	Inspection and Properties:

In [14]:
print("Shape:", temperatures_w1.shape)

Shape: (7,)


In [15]:
print("dtype:",temperatures_w1.dtype)

dtype: float64


In [43]:
print("size & Number of elements:", temperatures_w1.size)

size & Number of elements: 7


### 3.	Array Operations:

In [17]:
temperatures_in_Fahrenheit = (temperatures_w1 * 9/5) + 32
temperatures_in_Fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [22]:
max_temp = np.max(temperatures_in_Fahrenheit)
print("Maximum temperatures of the week :",max_temp)

Maximum temperatures of the week : 78.98


In [23]:
min_temp = np.min(temperatures_in_Fahrenheit)
print("Minimum temperatures of the week :",min_temp)

Minimum temperatures of the week : 69.44


In [24]:
avg_temp = np.mean(temperatures_in_Fahrenheit)
print("Average temperature of the week :",avg_temp)

Average temperature of the week : 74.37714285714286


### 4.	Array Slicing and Indexing:

In [30]:
first_three_days = temperatures_in_Fahrenheit[:3]
print("Temperatures for the first three days of the week:",first_three_days)

Temperatures for the first three days of the week: [72.5  77.54 69.44]


In [37]:
last_two_days = temperatures_in_Fahrenheit[5:]
print("Temperatures for the weekend (last two days):",last_two_days)

Temperatures for the weekend (last two days): [76.64 71.42]


In [38]:
middle_three_days = temperatures_in_Fahrenheit[1:-3]
print("Temperatures for the middle three days of the week:",middle_three_days)

Temperatures for the middle three days of the week: [77.54 69.44 74.12]


### 5.	Create a 2D Array:

In [42]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                         [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

### 6.	Inspect and Slice the 2D Array:

In [44]:
print("Shape:", temperatures.shape)

Shape: (2, 7)


In [45]:
print("dtype:",temperatures.dtype)

dtype: float64


In [46]:
print("size & Total number of elements:", temperatures.size)

size & Total number of elements: 14


In [52]:
first_week =temperatures[0]
print("The temperatures for the first week (Row 1):",first_week)

The temperatures for the first week (Row 1): [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [53]:
second_week =temperatures[1]
print("The temperatures for the second week (Row 2):",second_week)

The temperatures for the second week (Row 2): [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [57]:
first_three_days =temperatures[:, :3]
print("The temperatures for the first three days of each week:\n",first_three_days)

The temperatures for the first three days of each week:
 [[22.5 25.3 20.8]
 [19.2 22.5 21.3]]


In [58]:
weekends =temperatures [:, -2:]
print("The temperatures for the weekends (last two days) of both weeks:\n",weekends)

The temperatures for the weekends (last two days) of both weeks:
 [[24.8 21.9]
 [22.8 20.1]]
